up

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,10 +29,10 @@ jobs:
       
       - name: Clean directories
         run: |
-          rm -rf allure-results
-          rm -rf allure-report
-          npm run cy:clean
-      
+          echo "Cleaning directories..."
+          rm -rf allure-results allure-report
+          npm run cy:clean || echo "Clean script failed, but continuing."
+
       - name: Install dependencies
         run: npm install
         continue-on-error: true
