up

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -56,33 +56,34 @@ jobs:
           wait-on-timeout: 60
           start: npm run cy:e2e
         continue-on-error: true
-     
-      - name: Load test report history
-        if: steps.cypress.outcome == 'success' || steps.cypress.outcome == 'failure'
+      
+      - name: Check test results
+        if: steps.cypress.outcome == 'failure'
+        run: |
+          echo "Cypress tests failed"
+          exit 1
+
+  page-deployment:
+    runs-on: ubuntu-latest
+    needs: regression-cypress
+    steps:
+      - name: Checkout Report History
         uses: actions/checkout@v4
         continue-on-error: true
         with:
           ref: gh-pages
           path: gh-pages
       
-      - name: Build test report
-        if: steps.cypress.outcome == 'success' || steps.cypress.outcome == 'failure'
+      - name: Build Test Report
         uses: simple-elf/allure-report-action@v1.7
         with:
           gh_pages: gh-pages
           allure_history: allure-history
           allure_results: allure-results
       
-      - name: Publish test report
-        if: steps.cypress.outcome == 'success' || steps.cypress.outcome == 'failure'
+      - name: Publish Test Report
         uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_branch: gh-pages
           publish_dir: allure-history
-
-      - name: Check test results
-        if: steps.cypress.outcome == 'failure'
-        run: |
-          echo "Cypress tests failed"
-          exit 1
